// apps/docs/src/content/solid/demos/segment-group-demo/SegmentGroupBasicDemo.tsx
import { SegmentGroup, SegmentGroupItem } from "@ark-preset/solid";

export default function SegmentGroupBasicDemo() {
  return (
    <SegmentGroup defaultValue="React">
      <SegmentGroupItem value="React">React</SegmentGroupItem>
      <SegmentGroupItem value="Solid">Solid</SegmentGroupItem>
      <SegmentGroupItem value="Vue">Vue</SegmentGroupItem>
    </SegmentGroup>
  );
}

// apps/docs/src/components/demos/segment-group-demo/SegmentGroupBasicDemo.tsx
import { Index } from "solid-js";
import { DemoWrapper } from "../../DemoWrapper";
import { SegmentGroup, SegmentGroupItem } from "@ark-preset/solid";

const frameworks = ["React", "Solid", "Svelte", "Vue"];

export default function SegmentGroupBasicDemo() {
  return (
    <DemoWrapper class="space-y-6">
      <div>
        <p class="text-sm text-muted-foreground mb-2">Basic horizontal</p>
        <SegmentGroup defaultValue="React">
          <Index each={frameworks}>
            {(framework) => <SegmentGroupItem value={framework()}>{framework()}</SegmentGroupItem>}
          </Index>
        </SegmentGroup>
      </div>

      <div>
        <p class="text-sm text-muted-foreground mb-2">Vertical orientation</p>
        <SegmentGroup defaultValue="Solid" orientation="vertical">
          <Index each={frameworks}>
            {(framework) => <SegmentGroupItem value={framework()}>{framework()}</SegmentGroupItem>}
          </Index>
        </SegmentGroup>
      </div>
    </DemoWrapper>
  );
}
