// apps/docs/src/components/demos/radio-group-demo/RadioGroupBasicDemo.tsx
import { Index } from "solid-js";
import { DemoWrapper } from "../../DemoWrapper";
import { RadioGroup, RadioGroupItem } from "@ark-preset/solid";
const paymentMethods = [
  { value: "1", label: "Credit Card" },
  { value: "2", label: "Paypal" },
  { value: "3", label: "Debit" },
];
export default function RadioGroupBasicDemo() {
  return (
    <DemoWrapper>
      <RadioGroup defaultValue="1" orientation="horizontal">
        <Index each={paymentMethods}>
          {(method) => <RadioGroupItem value={method().value}>{method().label}</RadioGroupItem>}
        </Index>
      </RadioGroup>
    </DemoWrapper>
  );
}

// apps/docs/src/content/solid/demos/radio-group-demo/RadioGroupBasicDemo.tsx
import { RadioGroup, RadioGroupItem } from "@ark-preset/solid";

export default function RadioGroupBasicDemo() {
  return (
    <RadioGroup defaultValue="1" orientation="horizontal">
      <RadioGroupItem value="1">Credit Card</RadioGroupItem>
      <RadioGroupItem value="2">Paypal</RadioGroupItem>
      <RadioGroupItem value="3">Debit</RadioGroupItem>
    </RadioGroup>
  );
}
