// packages/solid/src/input/index.tsx
import { Field as ArkField } from "@ark-ui/solid/field";
import { splitProps, type Component, type JSX } from "solid-js";
import { InputRoot, InputLabel, InputField, InputDescription, InputErrorText } from "./input.base";
import { InputVariants } from "@ui/core";

type InputProps = {
  label?: string;
  description?: string;
  class?: string;
  children?: JSX.Element;
} & ArkField.InputProps &
  InputVariants;

export const Input: Component<InputProps> = (props) => {
  const [local, others] = splitProps(props, ["class", "label", "description", "error", "children"]);
  return (
    <InputRoot class={local.class} invalid={!!local.error}>
      {local.label && <InputLabel>{local.label}</InputLabel>}
      <InputField error={!!local.error} {...others} />
      {local.description && !local.error && (
        <InputDescription>{local.description}</InputDescription>
      )}
      {local.error && <InputErrorText>{local.error}</InputErrorText>}
      {local.children}
    </InputRoot>
  );
};

export * from "./input.base";

export { inputVariants, type InputVariants } from "@ui/core";

// packages/react/src/input.tsx
import { forwardRef, type InputHTMLAttributes } from "react";
import { Field } from "@ark-ui/react/field";
import { inputVariants } from "@ui/core/recipes/input";

type InputProps = {
  label?: string;
  description?: string;
  error?: string;
  className?: string;
} & InputHTMLAttributes<HTMLInputElement>;

const Input = forwardRef<HTMLInputElement, InputProps>(
  ({ label, description, error, className, ...props }, ref) => {
    const styles = inputVariants({ error: !!error });
    return (
      <Field.Root className={styles.root({ class: className })} invalid={!!error}>
        {label && <Field.Label className={styles.label()}>{label}</Field.Label>}
        <Field.Input className={styles.input()} ref={ref} {...props} />
        {description && !error && (
          <Field.HelperText className={styles.description()}>{description}</Field.HelperText>
        )}
        <Field.ErrorText className={styles.error()}>{error}</Field.ErrorText>
      </Field.Root>
    );
  },
);
Input.displayName = "Input";

export { Input, inputVariants };
export type { InputProps };
